"""empty message

Revision ID: 20004db77d5e
Revises: adb8fef78889
Create Date: 2020-05-17 23:32:53.583981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20004db77d5e'
down_revision = 'adb8fef78889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('artists', sa.Column('start_date', sa.Date(), nullable=True))
    op.drop_column('artists', 'availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('availability', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'start_date')
    op.drop_column('artists', 'end_date')
    # ### end Alembic commands ###
