"""empty message

Revision ID: 2d0e07443cd2
Revises: f1dd5e513d14
Create Date: 2020-05-19 22:55:30.818750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0e07443cd2'
down_revision = 'f1dd5e513d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created')
    op.drop_column('artists', 'created')
    # ### end Alembic commands ###
