"""empty message

Revision ID: 63b9a1c65340
Revises: b84f9b30a74e
Create Date: 2020-05-19 01:43:36.773161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b9a1c65340'
down_revision = 'b84f9b30a74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busy_times',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'start_date', 'end_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('busy_times')
    # ### end Alembic commands ###
