"""empty message

Revision ID: adb8fef78889
Revises: 41f1ebbcac0c
Create Date: 2020-05-17 22:17:51.924162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb8fef78889'
down_revision = '41f1ebbcac0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('availability', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'availability')
    # ### end Alembic commands ###
