"""empty message

Revision ID: b84f9b30a74e
Revises: 20004db77d5e
Create Date: 2020-05-19 00:26:28.438611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84f9b30a74e'
down_revision = '20004db77d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('availability', sa.String(length=120), nullable=True))
    op.drop_column('artists', 'start_date')
    op.drop_column('artists', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'availability')
    # ### end Alembic commands ###
